### PR TITLE
Fix the return annotation for fetch_access_token

### PR DESCRIPTION
**Pull request by sampart**
As you can see by the return value in the function, it returns an array, not a string.  Thought it worth changing to avoid IDEs incorrectly autocompleting annotations for other functions which call this.

### CODE REVIEW

**Comment by timrogers** [comment]
@sampart Thanks for the PR, we really appreciate it.

What are you seeing returned in the array? Is it just `["access_token"]` or was there something else in there too?

**Comment by sampart** [comment]
@timrogers Good point.  I was so focused on changing the return type, that I didn't update the description too.  I've done that now.

**Comment by timrogers** [comment]
Sounds reasonable! I'll get this merged in next time I release an update.

**Comment by sampart** [comment]
Thanks!

**Pull request merged**
