### PR TITLE
Update docblock for confirm_resource

### LINKED ISSUE #39: Docblock on GoCardless:confirm_resource() is wrong
It's just a copy of the docblock from GoCardless::new_bill_url()

### PR DESCRIPTION
**Pull request by petehamilton**
@jackfranklin ?

Fixes #39, needed to match https://github.com/gocardless/gocardless-php/blob/84250eb38c0eff2f33356419a03e3509bb89ce00/lib/GoCardless/Client.php#L268

### CODE REVIEW

**Comment by jacobpgn** [comment]
@petehamilton Almost! It actually returns the object that it just confirmed, ie a Bill, a Subscription or a PreAuthorization object

**Comment by petehamilton** [comment]
@jacobpgn In that case it's wrong in two places. Can you update on this branch?

**Comment by jacobpgn** [comment]
@petehamilton How's that?

**Comment by petehamilton** [comment]
:+1: Not sure why the specs are failing though...

**Comment by jacobpgn** [comment]
Looks like a long-standing issue, I'll get that fixed

**Pull request merged**
