### PR TITLE
Update composer instructions now that the repository has moved.

### PR DESCRIPTION
**Pull request by sampart**

### CODE REVIEW

**Comment by timrogers** [comment]
I don't think this should be needed as we're intending that people download this from Packagist (see [here](https://packagist.org/packages/gocardless/gocardless)) - unless I'm missing something?

**Comment by sampart** [comment]
The problem is that the Packagist entry references https://github.com/gocardless/gocardless-php, which is now just a disambiguation repository which doesn't actually contain any code or release.

For example, I recently tried to build my vendors from scratch (as part of CI) and got this error:

```
  - Installing gocardless/gocardless (0.4.2)
    Downloading: Connecting...    Downloading: 0%               Downloading: Failed
    Failed to download gocardless/gocardless from dist: The "https://api.github.com/repos/gocardless/gocardless-php/zipball/4698e9b08172697360938f4e8b30dce93cc76ee7" file could not be downloaded (HTTP/1.1 302 Found)
    Now trying to download from source
  - Installing gocardless/gocardless (0.4.2)
    Cloning 4698e9b08172697360938f4e8b30dce93cc76ee7
    4698e9b08172697360938f4e8b30dce93cc76ee7 is gone (history was rewritten?)


  [RuntimeException]                                                           
  Failed to execute git checkout '4698e9b08172697360938f4e8b30dce93cc76ee7' -  
  - && git reset --hard '4698e9b08172697360938f4e8b30dce93cc76ee7' --          
  fatal: reference is not a tree: 4698e9b08172697360938f4e8b30dce93cc76ee7     
```

They'd worked previously, but you've obviously now rearranged your Github repos.  I therefore had to add the `repositories` entry (and do a `composer update gocardless/gocardless` to update my `composer.lock`) to get this to work.

**Comment by timrogers** [comment]
@sampart Makes sense! Can you try again now without that? I've just updated the data in Packagist which might fix it I suspect.

**Comment by timrogers** [comment]
(P.S. Thanks for making a PR with this - good to know if we've accidentally broken something!)

**Comment by sampart** [comment]
Thanks for updating Packagist, @timrogers.  That does indeed solve it, so I'll close this PR.  Thanks for the fix!

**Pull request closed without merging**
