### PR TITLE
Allow the referrer (via the 'r' parameter) to be passed without signatur...

### PR DESCRIPTION
**Pull request by rquadling**
...e failure.

### CODE REVIEW

**Comment by timrogers** [comment]
@RQuadling What are you using the `r` parameter for?

**Comment by rquadling** [comment]
The referrer code. Attached to the merchant signups and to payees.

With the merchant signup, we append our 'state' and 'r' (referral code) and the merchant is then 'tagged' to us for referrals. No need to alter the GoCardless code base here as their is no signature checking being done on the appended data at your end.

With the payment side of things, appending the referral code in the same way breaks the signature of the supplied data. By allowing 'r' to be excluded from the signature, the referral code is passed through and the payee get the referral cookie. And if they sign up as a merchant then again, we are tagged for referrals.

You can see the user gets cookie dropped with the referral_code when either of these processes are used.

I hope that makes sense.

**Comment by timrogers** [comment]
Ah, that makes sense! Would you mind dropping me a quick email at tim at
gocardless dot com please?

## 

Tim Rogers

GoCardless Ltd
020 7183 8674

**Comment by timrogers** [comment]
We don't currently support this option in the API. Closing.

**Pull request closed without merging**
